services:
  opengenomebrowser:
    image: docker.abrinca.com/opengenomebrowser:latest
    env_file:
      - production.env
    container_name: opengenomebrowser
    ports:
      - "8080:8080" # nginx (HTTP)
      - "4443:4443" # nginx (HTTPS)
    volumes:
      - ./ogb_container:/data:Z
