services:
  opengenomebrowser:
    image: docker.abrinca.com/opengenomebrowser:latest
    env_file:
      - production-template.env
    container_name: opengenomebrowser
    environment:
      - POSTGRES_DB=opengenomebrowser_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    ports:
      - "8080:8080"   # nginx (HTTP)
      - "4443:4443"   # nginx (HTTPS)
    volumes:
      - ./ogb_container:/data
